In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("Array 1D:",arr_1d,arr_1d.dtype)

Array 1D: [1 2 3 4 5] int64


In [3]:
zeros = np.zeros([1,2,3])
ones = np.ones([3,3])
print("\nArray Zeros:\n", zeros)
print("\nArray Ones:\n",ones)


Array Zeros:
 [[[0. 0. 0.]
  [0. 0. 0.]]]

Array Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
arr_range = np.arange(0, 10, 1.5)
print("\nArray Arange: ", arr_range)


Array Arange:  [0.  1.5 3.  4.5 6.  7.5 9. ]


In [5]:
arr_lin = np.linspace(0,1,5)
print("\nArray Linspace:",arr_lin)


Array Linspace: [0.   0.25 0.5  0.75 1.  ]


In [6]:
sample_arr = np.array([[1.5,2.3, 4.0],[5.1,6.2,7.3]])
print("Array:")
print(sample_arr)

Array:
[[1.5 2.3 4. ]
 [5.1 6.2 7.3]]


In [7]:
print("Tipe Data (dtype):", sample_arr.dtype)
print("Dimensi (ndin):", sample_arr.ndim)
print("Ukuran / shape:", sample_arr.shape)
print("Total Elemen (size):", sample_arr.size)

Tipe Data (dtype): float64
Dimensi (ndin): 2
Ukuran / shape: (2, 3)
Total Elemen (size): 6
