In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("Array 1D:",arr_1d,arr_1d.dtype)

Array 1D: [1 2 3 4 5] int64


In [3]:
zeros = np.zeros([1,2,3])
ones = np.ones([3,3])
print("\nArray Zeros:\n", zeros)
print("\nArray Ones:\n",ones)


Array Zeros:
 [[[0. 0. 0.]
  [0. 0. 0.]]]

Array Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
arr_range = np.arange(0, 10, 1.5)
print("\nArray Arange: ", arr_range)


Array Arange:  [0.  1.5 3.  4.5 6.  7.5 9. ]


In [5]:
arr_lin = np.linspace(0,1,5)
print("\nArray Linspace:",arr_lin)


Array Linspace: [0.   0.25 0.5  0.75 1.  ]


In [6]:
sample_arr = np.array([[1.5,2.3, 4.0],[5.1,6.2,7.3]])
print("Array:")
print(sample_arr)

Array:
[[1.5 2.3 4. ]
 [5.1 6.2 7.3]]


In [7]:
print("Tipe Data (dtype):", sample_arr.dtype)
print("Dimensi (ndin):", sample_arr.ndim)
print("Ukuran / shape:", sample_arr.shape)
print("Total Elemen (size):", sample_arr.size)

Tipe Data (dtype): float64
Dimensi (ndin): 2
Ukuran / shape: (2, 3)
Total Elemen (size): 6


In [8]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Matriks Asli: ",arr)

Matriks Asli:  [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [9]:
print("Baris Pertama:",arr[2, :])

Baris Pertama: [70 80 90]


In [10]:
print("\nElemen baris 1, kolom 2:", arr[1,2])


Elemen baris 1, kolom 2: 60


In [11]:
print("Kolom terakhir:", arr[:,-1])

Kolom terakhir: [30 60 90]


In [12]:
print("sub-matriks 2x2 bawah:\n", arr[1:,1:])

sub-matriks 2x2 bawah:
 [[50 60]
 [80 90]]


# 4.Operasi Matematika & Broadcasting
#### NumPy memungkinkan opeasi aritmatika dilakukan secara langsung ke setiap elemen (element-wise).

In [13]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [14]:
print("Penjumlahan ([a+b]):",a+b)

Penjumlahan ([a+b]): [11 22 33]


In [15]:
print("Perkalian skalar (a * 2):",a*2)

Perkalian skalar (a * 2): [2 4 6]


In [16]:
print("Akar Kuadrat b (np.sqrt):", np.sqrt(b))

Akar Kuadrat b (np.sqrt): [3.16227766 4.47213595 5.47722558]


In [17]:
print("nila rata-rata b:",np.mean(b))

nila rata-rata b: 20.0


In [18]:
print("Standar deviasi b:",np.std(b))

Standar deviasi b: 8.16496580927726


# 5. Manipulasi Shape

In [19]:
flat_arr = np.arange(1,13)
print("Array 1D asli:", flat_arr)

Array 1D asli: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
reshaped_arr = flat_arr.reshape(3,4)
print("\nHasil Reshape 3x4:\n",reshaped_arr)


Hasil Reshape 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
back_to_flat = reshaped_arr.flatten()
print("\nHasil Flatten:",back_to_flat)


Hasil Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
nilai = np.array([
    [85,90,88],
    [70,80,75],
    [95,95,100],
    [60,65,70],
    [80,85,80]
])

rata_mapel = np.mean(nilai, axis=0)
print("Rata-rata Nilai (Matematika, Fisika, Kimia):")
print(rata_mapel)

Rata-rata Nilai (Matematika, Fisika, Kimia):
[78.  83.  82.6]


In [23]:
rata_siswa = np.mean(nilai,axis=1)
print("Rata-rata nilai per Siswa (A,B,C,D,E):")
print(rata_siswa)

Rata-rata nilai per Siswa (A,B,C,D,E):
[87.66666667 75.         96.66666667 65.         81.66666667]


In [24]:
nilai_tertinggi = np.max(nilai, axis=0)
print("\nNilai tertinggi tiap Mapel:", nilai_tertinggi)


Nilai tertinggi tiap Mapel: [ 95  95 100]


In [25]:
#data sampel : Dadtaset tinggi badan (cm) dan berat badan (kg) dari 5 orang
data = np.array([
    [175, 70],
    [160, 55],
    [180, 85],
    [165, 60],
    [170, 68]
])

In [26]:
#Cari nilai minimum dan maksimum untuk setiap kolom
data_min = np.min(data, axis=0)
data_max = np.max(data, axis=0)

#melakukan Min-Max scalling (Broadcasting secara otomatis bekerja di sini)
data_scaled = (data-data_min) / (data_max-data_min)

In [27]:
print("Data Asli (Tinggi , Berat):\n", data)
print("\nNilai Min tiap kolom: ", data_min)
print("Nilai Max tiap kolom:", data_max)
print("\nData setelah dinormalisasi (Skala 0-1):\n", np.round(data_scaled,4))

Data Asli (Tinggi , Berat):
 [[175  70]
 [160  55]
 [180  85]
 [165  60]
 [170  68]]

Nilai Min tiap kolom:  [160  55]
Nilai Max tiap kolom: [180  85]

Data setelah dinormalisasi (Skala 0-1):
 [[0.75   0.5   ]
 [0.     0.    ]
 [1.     1.    ]
 [0.25   0.1667]
 [0.5    0.4333]]


# misalnya kita memiliki data volume penjualan harian selama 10 hari. Kita ingin menyaring hari-hari diatas rata dan menghitung total penjualan pada hari-hari tersebut

In [28]:
#volumen penjualan selama 30 hari
penjualan = np.array([100, 85, 150, 200, 95, 100, 75, 210, 130])
hari = np.arange(1,10)

In [29]:
#1. Hitung rata-rata penjualan
rata_penjualan = np.mean(penjualan)
print(f"rata-rata penjualan harian: {rata_penjualan} data")

rata-rata penjualan harian: 127.22222222222223 data


In [30]:
#2. Buat boolean mask untuk mendeteksi penjualan diatas rata-rata
mask_di_atas_rata = penjualan > rata_penjualan
print("\nBoolean Mask (Penjualan > Rata-rata):\n", mask_di_atas_rata)


Boolean Mask (Penjualan > Rata-rata):
 [False False  True  True False False False  True  True]


In [31]:
#3 Filter data menggunakan mask tersebut
hari_performa_tinggi = hari[mask_di_atas_rata]
penjualan_performa_tinggi = penjualan[mask_di_atas_rata]

print(f"\nHari-hari dengan penjualan diatas rata-rata: hari ke-{hari_performa_tinggi}")


Hari-hari dengan penjualan diatas rata-rata: hari ke-[3 4 8 9]


In [32]:
print(f"\nNilai penjualan pada hari tersebut: {penjualan_performa_tinggi}")
print(f"\nTotal penjualan yang didapat dari hari-hari performa tinggi tersebut:{np.sum(penjualan_performa_tinggi)}unit")


Nilai penjualan pada hari tersebut: [150 200 210 130]

Total penjualan yang didapat dari hari-hari performa tinggi tersebut:690unit
