In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("Array 1D:",arr_1d,arr_1d.dtype)

Array 1D: [1 2 3 4 5] int64


In [3]:
zeros = np.zeros([1,2,3])
ones = np.ones([3,3])
print("\nArray Zeros:\n", zeros)
print("\nArray Ones:\n",ones)


Array Zeros:
 [[[0. 0. 0.]
  [0. 0. 0.]]]

Array Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
arr_range = np.arange(0, 10, 1.5)
print("\nArray Arange: ", arr_range)


Array Arange:  [0.  1.5 3.  4.5 6.  7.5 9. ]


In [5]:
arr_lin = np.linspace(0,1,5)
print("\nArray Linspace:",arr_lin)


Array Linspace: [0.   0.25 0.5  0.75 1.  ]


In [6]:
sample_arr = np.array([[1.5,2.3, 4.0],[5.1,6.2,7.3]])
print("Array:")
print(sample_arr)

Array:
[[1.5 2.3 4. ]
 [5.1 6.2 7.3]]


In [7]:
print("Tipe Data (dtype):", sample_arr.dtype)
print("Dimensi (ndin):", sample_arr.ndim)
print("Ukuran / shape:", sample_arr.shape)
print("Total Elemen (size):", sample_arr.size)

Tipe Data (dtype): float64
Dimensi (ndin): 2
Ukuran / shape: (2, 3)
Total Elemen (size): 6


In [8]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Matriks Asli: ",arr)

Matriks Asli:  [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [9]:
print("Baris Pertama:",arr[2, :])

Baris Pertama: [70 80 90]


In [10]:
print("\nElemen baris 1, kolom 2:", arr[1,2])


Elemen baris 1, kolom 2: 60


In [11]:
print("Kolom terakhir:", arr[:,-1])

Kolom terakhir: [30 60 90]


In [12]:
print("sub-matriks 2x2 bawah:\n", arr[1:,1:])

sub-matriks 2x2 bawah:
 [[50 60]
 [80 90]]


# 4.Operasi Matematika & Broadcasting
#### NumPy memungkinkan opeasi aritmatika dilakukan secara langsung ke setiap elemen (element-wise).

In [13]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [14]:
print("Penjumlahan ([a+b]):",a+b)

Penjumlahan ([a+b]): [11 22 33]


In [15]:
print("Perkalian skalar (a * 2):",a*2)

Perkalian skalar (a * 2): [2 4 6]


In [16]:
print("Akar Kuadrat b (np.sqrt):", np.sqrt(b))

Akar Kuadrat b (np.sqrt): [3.16227766 4.47213595 5.47722558]


In [17]:
print("nila rata-rata b:",np.mean(b))

nila rata-rata b: 20.0


In [18]:
print("Standar deviasi b:",np.std(b))

Standar deviasi b: 8.16496580927726


# 5. Manipulasi Shape